import React, { useEffect, useState } from 'react';
import { causariumApi } from '../services/api';

export const RealityReport: React.FC<{ simulationId: string; onClose: () => void }> = ({ simulationId, onClose }) => {
  const [report, setReport] = useState<any>(null);

  useEffect(() => {
    causariumApi.generateReport(simulationId).then(setReport);
  }, [simulationId]);

  return (
    <div className="absolute inset-0 bg-[#0A0A0F]/90 backdrop-blur-md flex items-center justify-center p-8 z-50">
      <div className="bg-white text-black rounded-lg w-full max-w-4xl h-5/6 shadow-2xl flex flex-col overflow-hidden relative">
        
        <div className="flex justify-between items-center p-6 border-b border-gray-200 bg-gray-50">
          <div>
            <h2 className="text-2xl font-serif text-gray-900">CAUSARIUM Reality Report</h2>
            <p className="text-sm text-gray-500 mt-1 font-mono uppercase">Simulation: {simulationId}</p>
          </div>
          <div className="flex space-x-4">
            <button className="bg-[#6C63FF] text-white px-4 py-2 rounded text-sm hover:bg-[#5a52d6] transition-colors">Download PDF</button>
            <button onClick={onClose} className="text-gray-500 hover:text-gray-900">&times;</button>
          </div>
        </div>

        {!report ? (
          <div className="flex-1 flex items-center justify-center text-gray-400 animate-pulse">Generating PDF layout...</div>
        ) : (
          <div className="flex-1 p-12 overflow-y-auto bg-white font-serif text-gray-800 space-y-8">
            <div className="border-l-4 border-[#6C63FF] pl-6 mb-8">
              <h1 className="text-4xl font-light mb-4 text-gray-900">Executive Summary</h1>
              <p className="text-lg leading-relaxed text-gray-700">
                This report summarizes the emergent causal structures discovered across 200 parallel simulation timelines. 
                Our discovery engine identified 3 dominant attractors, with a 67% probability of convergence on regulatory 
                consolidation regardless of early-stage strategic interventions.
              </p>
            </div>

            <hr className="border-gray-200" />

            <div>
              <h3 className="text-2xl font-light mb-4">Critical Windows & Interventions</h3>
              <p className="mb-4">Temporal choke points were identified primarily in Ticks 7-14. Intervention efficacy decays rapidly after Tick 14.</p>
              
              <div className="bg-gray-50 p-6 rounded border border-gray-200 font-sans">
                <div className="font-semibold text-[#00D9FF] mb-2 uppercase text-sm tracking-wider">Top Recommended Action</div>
                <div className="text-lg mb-2">CEO Communications Pivot @ Tick 7</div>
                <div className="text-sm text-gray-600">Injecting a confidence modification at this juncture re-routes 42% of negative timelines into Attractor A (Market Dominance).</div>
              </div>
            </div>
            
            <div className="text-center text-gray-400 text-sm italic pt-12">
              Generated by CAUSARIUM Reality Intelligence Platform<br/>
              Confidential – Not for external distribution
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
